name: "paraphrase_embedder"
backend: "onnxruntime"
max_batch_size: 0

parameters {
  key: "execution_providers"
  value: { string_value: "CUDAExecutionProvider" }
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
